name: Generate snake animation

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate snake.svg
        run: |
          npx create-snake-svg -o dist/snake.svg

      - name: Commit changes
        run: |
          git config --global user.email "Chaitanya-2406@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/snake.svg
          git commit -m "Generate snake.svg"
      
      - name: Push changes
        uses: ad-m/github-push-action@Chaitanya-2406
        with:
          branch: output
