name: Generate snake animation

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Chaitanya-2406
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: ad-m/github-push-action@master
        with:
          branch: output
          directory: dist
        env:
          GITHUB_TOKEN: ${{ secrets.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  }}
